### ISSUE TITLE
MyPage

### ISSUE THREAD

**Issue by Hashswim** [marimorimo/RimoRimo#5]
### to-do
- [x] 유저 데이터 마이페이지 표시
- [x] 획득 마리모 컬렉션 표시
- [x] 보유 마리모 데이터 애니메이션 적용
